name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout tests
      uses: actions/checkout@v4
      with:
        repository: IR1-2024/hidden-tests-assignment1-part1
        ref: main
        token: ${{ secrets.A1P1 }}
        path: tests
    - uses: actions/setup-python@v4
      with:
          python-version: '3.10.12'
          cache: 'pip'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Download CACM dataset
      run: |
          if ! [ -f "./datasets/qrels.text" ];
            then
                python download_dataset.py
          fi
    - name: Autograding
      uses: education/autograding@v1
