name: assignment2-part2
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.10.12
  - pip:
      - gensim==4.3.1
      - matplotlib==3.7.2
      - nltk==3.8.1
      - numpy==1.25.2
      - pytest==7.4.0
      - requests==2.31.0
      - tqdm==4.66.1
      - torch==2.1.2
      - pandas~=1.4.2
      - pathlib==1.0.1