name: assignment2-part1
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - pytest==7.2.1
  - requests>=2.28.2,<2.29.0
  - tqdm>=4.64.1,<4.65.0
  - numpy>=1.24.1,<1.25.0
  - pytorch
  - pandas>=1.4.2,<1.5.0
  - nltk>=3.7,<3.8.0
  - matplotlib>=3.5.1,<3.6.0
  - notebook
  - path