name: assignment1-part2
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.10.12
  - pip:
      - faiss-cpu==1.7.4
      - torch==2.0.1
      - ir-measures==0.3.3
      - jupyter==1.0.0
      - pyserini==0.21.0
      - pytest==7.4.0
      - tokenizers==0.13.3
      - transformers==4.29.0
